### PR TITLE
Issue49

### PR DESCRIPTION
**Pull request by RJ-Clegg**
Related to [issue 49](https://github.com/RocketFanOrg/RocketFanApp/issues/49)

Since there was an issue with 'Launch' model and the JSON response - (Nullability of a field changing) - as part of this fix I also updated all other local JSON files and ran tests to find any potential issues. 

Thankfully it was just the `Launch` model.

### CODE REVIEW

**Comment by squarefrog** [comment]
I’m out at the moment so can’t check, but does it make sense having a timeline event with a nil time?

**Comment by RJ-Clegg** [comment]
> I’m out at the moment so can’t check, but does it make sense having a timeline event with a nil time?

A timeline has many values, in this case, `webcast_liftoff` can be null, where as the other values in the timeline are for now) non null.

**Comment by squarefrog** [comment]
Ah ok. So I guess our options are either filter then on the way in, or the way out. 

I’d probably prefer we filter them on the way in as we’ll end up with less optionals. What are your thoughts? 

This can be in a new PR as we can deal with that later :+1:

**Comment by RJ-Clegg** [comment]
Sounds fine to me. I can filter it out.

**Pull request merged**
